packages:
  - app/*
  - lib/*

onlyBuiltDependencies:
  - '@esbuild/darwin-arm64'
  - '@isaacs/cliui'
  - '@jridgewell/gen-mapping'
  - '@jridgewell/resolve-uri'
  - '@jridgewell/set-array'
  - '@jridgewell/sourcemap-codec'
  - '@jridgewell/trace-mapping'
  - '@pkgjs/parseargs'
  - '@rollup/rollup-darwin-arm64'
  - '@types/estree'
  - '@vitest/expect'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/runner'
  - '@vitest/snapshot'
  - '@vitest/spy'
  - '@vitest/utils'
  - ansi-regex
  - ansi-styles
  - any-promise
  - assertion-error
  - balanced-match
  - brace-expansion
  - bundle-require
  - cac
  - chai
  - check-error
  - chokidar
  - color-convert
  - color-name
  - commander
  - consola
  - cross-spawn
  - debug
  - deep-eql
  - eastasianwidth
  - emoji-regex
  - es-module-lexer
  - esbuild
  - estree-walker
  - expect-type
  - fdir
  - foreground-child
  - fsevents
  - glob
  - is-fullwidth-code-point
  - isexe
  - jackspeak
  - joycon
  - lilconfig
  - lines-and-columns
  - load-tsconfig
  - lodash.sortby
  - loupe
  - lru-cache
  - magic-string
  - minimatch
  - minipass
  - ms
  - mz
  - nanoid
  - object-assign
  - package-json-from-dist
  - path-key
  - path-scurry
  - pathe
  - pathval
  - picocolors
  - picomatch
  - pirates
  - postcss
  - postcss-load-config
  - punycode
  - readdirp
  - resolve-from
  - rimraf
  - rollup
  - shebang-command
  - shebang-regex
  - siginfo
  - signal-exit
  - source-map
  - source-map-js
  - stackback
  - std-env
  - string-width
  - strip-ansi
  - sucrase
  - thenify
  - thenify-all
  - tinybench
  - tinyexec
  - tinyglobby
  - tinypool
  - tinyrainbow
  - tinyspy
  - tr46
  - tree-kill
  - ts-interface-checker
  - tsup
  - turbo
  - turbo-darwin-arm64
  - typescript
  - vite
  - vite-node
  - vitest
  - webidl-conversions
  - whatwg-url
  - which
  - why-is-node-running
  - wrap-ansi
